config/routes.rb
YentaFriend::Application.routes.draw do
  


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins
  mount RailsAdmin::Engine => '/manage', :as => 'rails_admin'

  get "paypal_express/checkout"
	post "paypal_express/handle_response"
	get "paypal_express/authenticate_redirect"

  match '/fb_handler/request_callback/:profile_type' => 'fb_handler#request_callback', :as => 'fb_callback'

  resources :profiles do
    member do
      post 'invite'
    end
  end
  
  scope :controller => :dashboard do
    match "login"
    match "dashboard"
    match "welcome"
    match "contacts"
    match "browse"
    match "inbox"
    match "matchbook"
    match "initialize_profile"
    match "send_invite"
    match "add_catch"
    match "suggest_match"
    match "approve_match"
    match "reject_match"
    match "message"
    match "endorsements"
    match "account"
  end
  
  scope :controller => :conversations do
    match "send_message"
    match "conversation/:id" => :show, :as => "conversation"
  end
  
  resources :connections
  match 'create_match' => 'profiles#create_match'
  
  match "project" => 'static_pages#project'
  match "team" => 'static_pages#team'
  match "login" => 'static_pages#login'
  
  match 'dashboard' => 'yenta_friend#dashboard'
  match 'browse' => 'yenta_friend#browse'
  # match 'connections' => 'yenta_friend#connections'
  match 'chickstud_connections(/:id)' => 'yenta_friend#chickstud_connections', :as => :chickstud_connections
  match 'inbox' => 'yenta_friend#inbox'
  match 'stable' => 'yenta_friend#stable'
  
  
  
  
  root :to => 'dashboard#login'
    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:login]
  skip_before_filter :authenticate_active!, :only => [:welcome, :initialize_profile]
  
  before_filter :restrict_access, :only => [:matchbook]
  
  # fiters
  def restrict_access
    redirect_to dashboard_path unless usertype[Regexp.new("yentum", true)]
  end
  
  # actions
  def login
    redirect_to dashboard_path if (user_signed_in? && current_profile && current_profile.active)
  end
  
  def account
    @profile = current_profile
    render 'profiles/show'
  end
  
  def dashboard
    
  end
  
  def welcome
    
  end
  
  def contacts
    
  end
  
  def browse
    
  end
  
  def refresh_connections
    redirect_to :back
  end
  
  def add_catch
    @endorsement = Endorsement.new(params[:endorsement])
    @endorsement.yentum = current_profile
    if @endorsement.save
      flash[:notice] = "#{@endorsement.chickstud.name} has been added to your matchbook!"
    else
      flash[:error] = "There was a problem in adding #{@endorsement.chickstud.name} to your matchbook..."
    end
    redirect_to :back
  end
  
  def suggest_match
    match = params[:match]
    @chickstuds = Profile.find(match[:chickstuds].collect{|c| c[1]}).to_a.compact.uniq
		if @chickstuds.many?
    	approval_ids = match[:approvals].to_a.collect{|a| a[1]}
	    @approval_profiles = Profile.find(approval_ids)
	    @match = Match.new(:owner => current_profile, :chickstuds => @chickstuds)
	    @approval_profiles.each do |profile|
	      @match.approvals.build(:profile => profile)
	    end
	    @match.approvals.build(:profile => current_profile, :approved_at => Time.now)
	    @match.save!
			if @match.approvals.pending.none?
	      @connection = Connection.create(:partners => @match.chickstuds, :observers => @match.approvals.collect(&:profile))
	# this needs to be rewritten
	      @match.chickstuds.each do |profile|
					# this is horrendous...
					matched_profile = (@match.chickstuds - profile.to_a).first
	        profile.links << (@match.chickstuds - profile.to_a)
					profile.notices.create(:header => "One of your Yentas has connected you with #{matched_profile.first_name}", :body => "Click on your Connections tab or the link to the right to view the connection", :href => connection_path(@connection._id), :icon_url => matched_profile.fb_image_url)
				
					Notifier.send_connection(matched_profile, profile.email, request.host_with_port, @connection, profile.first_name).deliver
	        profile.save
	      end
	    end
	    @conversation = Conversation.find(params[:conversation_id])
	    @conversation.messages.create(:messageable => @match, :from => current_profile.name, :icon_url => current_profile.image_url)
		else
			flash[:error] = "There was a problem"
		end
    redirect_to :back

  end
  
  def approve_match
    @match = Match.find(params[:match_id])
    if approval = @match.approvals.where(:profile_id => current_profile._id).first
      approval.update_attribute(:approved_at, Time.now)
    end
    @match.save
    if @match.approvals.pending.none?
			# make sure that the connection does not already exist
      @connection = Connection.create(:partners => @match.chickstuds, :observers => @match.approvals.collect(&:profile))
      @match.chickstuds.each do |profile|
				# this is horrendous...
				matched_profile =  (@match.chickstuds - profile.to_a).first
        profile.links << (@match.chickstuds - profile.to_a)
				profile.notices.create(:header => "One of your Yentas has connected you with #{matched_profile.first_name}", :body => "Click on your Connections tab or the link to the right to view the connection", :href => connection_path(@connection._id), :icon_url => matched_profile.fb_image_url)
				Notifier.send_connection(matched_profile, profile.email, @connection, request.host_with_port, profile.first_name).deliver
        profile.save
      end
    end
		flash[:notice] = "Match between #{@match.chickstuds.collect(&:first_name).join(" and ")} has been approved."
    redirect_to :back
  end
  def reject_match
    # @match = Match.find(params[:match_id])
    #     if approval = @match.approvals.where(:profile_id => current_profile._id).first
    #       approval.update_attribute(:approved_at, Time.now)
    #     end
    #     @match.save
  end
  
  def inbox
    @conversations = current_profile.conversations
  end
  
  def send_invite
    invite = params[:invite]
    current_user.invites.create(invite)
    Notifier.send_invite(current_profile, invite[:email],request.host_with_port, invite[:name], invite[:message]).deliver
    flash[:notice] = "Invitation to #{invite[:name]} (#{invite[:email]}) has been sent!"
  end

  def endorsements
    
  end

  def matchbook
    @endorsements = current_profile.endorsements
  end
  
  def initialize_profile
    @profile = current_user.profile
    @profile.update_attributes(:_type => params[:profile][:_type], :active => true)
    @linked_profiles = current_user.get_linked_profiles
    @profile.links << @linked_profiles
    @profile.save
    @profile.notices.create(:header => "Welcome to Yenta Friend", :body => "You have signed up as a #{@profile._type[/Yentum/] ? "Yenta" : "Catch" }.", :icon_url => @profile.fb_image_url)
    if @linked_profiles.any?
      @profile.notices.create(:header => "You have friends on Yenta!", :message => "We have found #{@linked_profiles.count} of your friends already on YentaFriend.  Click on your Contacts tab to view their profiles.", :href => contacts_path, :icon_url => 'icon_large.png')
      @linked_profiles.each do |profile|
        profile.links << @profile
        profile.notices.create(:header => "#{@profile.name} has joined the site as a #{@profile._type[/Yentum/] ? "Yenta" : "Catch" }", :message => "Check out #{@profile.pronoun_poss} profile!", :href => profile_path(@profile._id), :icon_url => @profile.image_url)
        profile.save
      end
    end
    redirect_to dashboard_path
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/browse.html.haml
= content_for :pageheader do
  %h1 Contacts
  %p.lead
    you currently have 
    %span{:class => "badge #{"badge-info" if @current_profile.links.count > 1 }"}= "#{@endorsements.count}/150"
    connections in your Yenta Network
      
= content_for :subnav do
  .subnav
    %ul.nav.nav-pills
      %li= link_to "yenta connections", '#yenta_connections', :class => 'anchorLink'
      %li= link_to "catch connections", '#chickstud_connections', :class => 'anchorLink'  
= content_for :main do
  %section#yenta_connections
    .page-header
      %h1
        yenta connections
        %small
          connect with other yentas and set up matches!
    .row
    
  
= content_for :modal do
  .modal#add_catch
    .modal-header
    .modal-body
      = form_for :add_catch, :url => add_catch_path do |f|
        .row
          .span4
            - for chickstud in current_profile.chickstud_links
              .span4
                %h4
                  = image_tag chickstud.fb_image_url, :width => "25px"
                  = chickstud.name
                .pull-right
                  = link_to_function "Select", "$('#selected_catch').html('#{escape_javascript()}')", :class => "btn"
          .span6
            %h2#selected_catch
            
          
          

app/views/dashboard/catchbook.html.haml
= content_for :pageheader do
  %h1 Matchbook
  %p.lead
    you currently have
    %span{:class => "badge #{"badge-info" if @endorsements.count > 1 }"}= "#{@endorsements.count}/5"
    friends in your Matchbook
      
= content_for :subnav do
  .subnav
    %ul.nav.nav-pills
      - @endorsements.collect(&:chickstud).compact.each_with_index do |chickstud, index|
        %li= link_to chickstud.first_name, "chickstud_#{chickstud._id}", :class => "anchorLink"
      - for i in (@endorsements.count..4).to_a
        %li= link_to "[add catch]", '#add_catch', "data-toggle" => "modal", :class =>"", :onclick => "$('#add_catch').modal();"
= content_for :main do
  - for endorsement in @endorsements do
    - chickstud = endorsement.chickstud
    - partner_connections = chickstud.partner_connections
    %section[chickstud]
      .page-header
        %h2
          = link_to profile_path(chickstud) do            
            = image_tag chickstud.image_url("large"), :width => "100px"
            = chickstud.name
          %small
            = "#{chickstud.first_name} has #{chickstud.partner_connections.count} connections"
      .row-fluid
        %hr
= content_for :modal do
  .modal#add_catch.hide
    .modal-header
      Pick a friend to add to your matchbook
    .modal-body
      - chickstud_links = current_profile.chickstud_links
      - if chickstud_links.any?
        = form_for :add_catch, :url => add_catch_path do |f|
          = f.hidden_field :chickstud_id
          .row
            .span4
              - for chickstud in chickstud_links
                .span4
                  %h4
                    = image_tag chickstud.image_url, :width => "25px"
                    = chickstud.name
                  .pull-right
                    = link_to_function "Select", "$('#add_catch_chickstud_id').val('#{chickstud._id}');$('#selected_catch').html('#{escape_javascript(chickstud.name)}'); ", :class => "btn"
            .span6
              %h2#selected_catch
              = f.label :endorsement
              = f.text_field :endorsement
              = f.submit
      - else 
        %h2 You don't have any friends =(
            
          
          

app/views/dashboard/chickstud_profile.html.haml
= content_for :pageheader do
  %h1
    = profile.name
  %p.lead
    = "Catch since #{timestamp_readable(profile.created_at)}"
= content_for :subnav do
  .subnav
    %ul.nav.nav-pills
      %li= link_to_function 'about', "$('#profile_information').html('#{escape_javascript(render :partial => 'profiles/info', :locals => {:profile => profile})}'); $('#profile_information').modal();", "data-toggle" => "modal"
      %li= link_to 'endorsements', "#endorsements", :class => 'anchorLink'
      %li= link_to 'conversation', "#conversation_#{@conversation._id}", :class => 'anchorLink'
      %li= link_to 'new message', "#new_message", :class => 'anchorLink'
= content_for :main do
  %section#endorsements
  .page-header
    %h1
      endorsements
      %small
        = "#{profile.first_name} has #{profile.endorsements.count} endorsements."
  .row-fluid
    - for endorsement in profile.endorsements
      - yentum = endorsement.yentum
      %h1
        = link_to profile_path(yentum) do
          %blockquote
            %em
              = image_tag yentum.fb_image_url
              = endorsement.message
            %small  
              = yentum.name
  %section[@conversation]
    .page-header
      %h2
        Conversation History
        %small="Your conversation with #{profile.first_name}"
      .row-fluid.message_wrapper
        - for message in @conversation.messages do
          = render :partial => 'conversations/messages/message', :locals => {:message => message}
  %section#new_message
    .page-header
      %h1 New Message
    .row
      = form_for :message, :class => "well form-search", :url => send_message_path, :remote => true do |f|
        = hidden_field_tag :conversation_id, @conversation._id
        = f.hidden_field :messageable_type
        = f.hidden_field :messageable_id
        / message will always be sent from the current user...
        - if usertype == "Yentum"  
          .span3
            = link_to "Send Profile", '#select_catch', "data-toggle" => "modal", :onclick => "$('#select_catch').modal();"
        .span3
          = f.text_field :body, :class => "input-xlarge search-query", :placeholder => "Send a message"
        = f.submit "Send"

app/views/dashboard/contacts.html.haml
= content_for :pageheader do
  %h1{:style => 'font-size:36px;margin-top:15px'} contacts
  %p.lead
    you currently have 
    %span{:class => "badge #{"badge-info" if current_profile.links.count > 1 }"}= "#{current_profile.links.count}/150"
    connections in your Yenta Network
      
= content_for :subnav do
  .subnav
    %ul.nav.nav-pills
      - if usertype == "Chickstud"
        %li= link_to "endorsements", "#endorsement_connections", :class => 'anchorLink'
      %li= link_to "yenta connections", '#yenta_connections', :class => 'anchorLink'
      - if usertype == "Yentum"
        %li= link_to "catch connections", '#chickstud_connections', :class => 'anchorLink'  
= content_for :main do
  - if usertype == "Chickstud"
    %section#endorsement_connections{:style=>'padding-top:0px'}
      .page-header
        %h1
          endorsements
          %small
      .row-fluid
        - for endorsement in current_profile.endorsements
          - yentum = endorsement.yentum
          %h1
            = link_to profile_path(yentum) do
              %blockquote
                %em
                  = image_tag yentum.fb_image_url
                  = endorsement.message
                %small  
                  = yentum.name
  %section#yenta_connections{:style=>'padding-top:0px'}
    .page-header
      %h1
        yenta connections
        %small
          check out their catches
    .row
      - for yentum in current_profile.yenta_links
        .span2
          = link_to profile_path(yentum) do
            .thumbnail
              = image_tag yentum.fb_image_url, :size => "150x150"
              .caption
                %h5= yentum.name
  - if usertype == "Yentum"          
    %section#chickstud_connections
      .page-header
        %h1
          catch connections
          %small
            find them some matches
      .row-fluid
        - for chickstud in current_profile.chickstud_links
          .span2{:height=>"75px"}
            = link_to profile_path(chickstud) do
              = image_tag chickstud.fb_image_url, :size => "170x170"
              %h3= chickstud.name                
          
      

app/views/dashboard/dashboard.html.haml
= content_for :pageheader do
	%h1{:style => 'font-size:36px;margin-top:15px'}
		dashboard  
		%span.lead see what's happening
= content_for :main do
	.row-fluid
		.span6#notices
			.well
				.page-header{:style=>'margin-top:0px'}
					%h2
						notices
						%small
							see what's important
							.pull-right{:style => 'margin-top:3px;'}
								%span.badge.badge-info{:style => 'font-size:16px'}= current_user_notices.count
								= "notice#{"s" unless current_user_notices.count == 1}"
				%ul
					- for notice in current_user_notices do
						= render :partial => 'shared/notice', :locals => {:notice => notice}
				
		.span6#messages
			.well
				.page-header{:style=>'margin-top:0px'}
					%h2 
						messages
						%small
							showing 5 most recently updated conversations
							/ %span.pull-right{:style => 'margin-top:3px;'}
							/ 	= link_to inbox_path do
							/ 		%span.badge.badge-info{:style=>'font-size:14px;padding-top:4px;padding-bottom:4px'}
							/ 			inbox
							/ 			%i.icon-chevron-right
				%ul
					- current_profile.conversations.where(:messages.ne => nil).limit(5).each do |conversation|
						- last_message = conversation.messages.first
						= render :partial => 'conversations/messages/message_abbr', :locals => {:message => last_message}
					/ - current_profile.conversations.where(:messages.ne => nil).collect(&:messages).flatten.compact.sort{|x,y| x.created_at <=> y.created_at}.each do |message|
					/ 	= render :partial => 'conversations/messages/message_abbr', :locals => {:message => message}						
	/ %section#friends
	/		- yentum_links = current_profile.links.where(:_type => "Yentum")
	/		.page-header
	/			%h1
	/				Yenta Friends
	/				%small
	/					See who you're connected to.
	/					= link_to 'Invite friends to join your Yenta Network', '#', :class => 'yenta_invite'
	/					.pull-right
	/						%span.badge= yentum_links.count
	/						yenta in your network
	/		.row
	/			- for profile in yentum_links do
	/				= render :partial => 'profiles/profile', :locals => {:profile => profile}
	/	%section#reserves
	/		- chickstud_links = current_profile.links.where(:_type => "Chickstud")
	/		.page-header
	/			%h1
	/				Chickstud Reserves
	/				%small
	/					See all the ChickStuds that you know
	/					= link_to 'Invite your friends so that you can match them!', '#', :class => 'chickstud_invite'
	/					.pull-right
	/						%span.badge= chickstud_links.count
	/						friends
	/		.row
	/			- for profile in chickstud_links do
	/				= render :partial => 'profiles/profile', :locals => {:profile => profile}	

app/views/dashboard/inbox.html.haml
= content_for :pageheader do
	%h1{:style => 'font-size:36px;margin-top:15px'}
		inbox
		%span.lead see your chats with others
= content_for :subheader do
	%ul
= content_for :main do
	%section#conversations{:style=>'padding-top:0px'}
		.well{:style=>'overflow:hidden'}
			.page-header
				%h1
					= "Listing #{@conversations.count} conversations"
					%small
						stay connected
						%span.pull-right{:style => 'margin-top:3px;'}
							%span.badge.badge-info{:style=>'font-size:14px;padding-top:4px;padding-bottom:4px'}
								inbox
								%i.icon-chevron-right
			%ul
				- current_profile.conversations.where(:messages.ne => nil).each do |conversation|
					- conversation.messages[0..4].each do |message|
						= render :partial => 'conversations/messages/message', :locals => {:message => message}

app/views/dashboard/initialize_profile.js.haml
$('#notice_wrapper').html("#{escape_javascript(render :partial => 'shared/flash')}");

app/views/dashboard/login.html.haml
%header.jumbotron.subhead.well
	%p.text-center#login
		=image_tag 'logo-full.png', :width => '350', :style => 'margin-bottom:15px'
	%hr
	%p.text-center
		=link_to "Log In With Facebook", user_omniauth_authorize_path(:facebook), :class => 'btn btn-primary btn-large'
	

app/views/dashboard/matchbook.html.haml
= content_for :pageheader do
	.row
		.span8
			%h1 matchbook
			%p.lead
				you currently have
				%span{:class => "badge #{"badge-info" if @endorsements.count > 1 }"}= "#{@endorsements.count}/5"
				friends in your Matchbook
		- unless current_profile.subscriber?
			.span4
				.alert.text-center
					%h2 Want more connections?
					= form_tag "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_blank" do
						%input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}
						%input{:name => "hosted_button_id", :type => "hidden", :value => paypal_link_id}
						= submit_tag "Upgrade to a Premium Account for  $1.00", :class => "btn btn-primary"
= content_for :subnav do
	.subnav
		%ul.nav.nav-pills
			- @endorsements.collect(&:chickstud).compact.each_with_index do |chickstud, index|
				%li= link_to chickstud.first_name, "#chickstud_#{chickstud._id}", :class => "anchorLink"
			- for i in ((@endorsements.count + 1)..[current_profile.matchbook_limit, 5].max).to_a
				%li= link_to "[add catch]", '#add_catch', "data-toggle" => "modal", :class =>"", :onclick => "$('#add_catch').modal();"
= content_for :main do
	- for endorsement in @endorsements do
		- chickstud = endorsement.chickstud
		- partner_connections = chickstud.partner_connections
		%section.profile[chickstud]
			.page-header
				%h2
					= link_to profile_path(chickstud) do
						.image_wrapper
							= image_tag chickstud.fb_image_url("large"), :size => "100x100"
						= chickstud.name
					%small
						= "#{chickstud.first_name} has #{chickstud.partner_connections.count} connections"
			.row-fluid
			
				%hr
= content_for :modal do
	.modal#add_catch.hide
		= form_for :endorsement, :url => add_catch_path do |f|
			= f.hidden_field :chickstud_id	
			.modal-header
				%a.close{"data-dismiss" => "modal"}x
				%h2
					Pick a friend to add to your matchbook
					%hr
					.well.alert
						%h2#selected_catch
						= f.label :message, "Endorsement"
						= f.text_field :message, :class => 'input-xlarge'
						= f.submit "Confirm Endorsement", :class => 'btn btn-large btn-primary'										
			.modal-body
				- chickstud_links = (current_profile.chickstud_links - @endorsements.collect(&:chickstud).compact.to_a)
				- if chickstud_links.any?
					%hr						
					.well{:style => "max-height:300px;y-overflow:scroll;"}
						%ul.list
							- chickstud_links.each do |chickstud|
								%li
									.row-fluid
										.span4=image_tag chickstud.fb_image_url, :size => "100x100"
										.span6
											%h1
												= chickstud.name
										.span2.sidelink
											%button.btn.btn-primary.btn-large{:style => "padding:10px;",:href => '#', :onclick => "$('#endorsement_chickstud_id').val('#{chickstud._id}');$('#selected_catch').html('#{escape_javascript(chickstud.name)}');return false"} Select
				- else 
					%h2 No friends were found.
						
					
					

app/views/dashboard/send_invite.js.haml
$('#notice_wrapper').html("#{escape_javascript(render :partial => 'shared/flash')}");
$('.modal').modal("hide");
$('#invite_form').html("#{escape_javascript(render :partial => 'shared/invite_form')}");

app/views/dashboard/welcome.html.haml
%header.jumbotron.masthead
  .inner
    .well
      = image_tag "logo_large.jpg", :width => "100%"    
      .hero-unit
        %h1
          Which type of profile would you like to create?
        .row
          = form_for :profile, :url => initialize_profile_path, :class => 'form form-vertical' do |f|
            .span8.offset2#profile_form.control-group
              .controls
                .input-append
                  = f.select :_type, options_for_select([["Yenta (match your friends!)","Yentum"], ["Catch (get matched!) ", "Chickstud"]]), :class =>'input input-xlarge span3', :size=>"60"
                  = f.submit "Go", :class => "btn btn-primary"