config/routes.rb
YentaFriend::Application.routes.draw do
  


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins
  mount RailsAdmin::Engine => '/manage', :as => 'rails_admin'

  get "paypal_express/checkout"
	post "paypal_express/handle_response"
	get "paypal_express/authenticate_redirect"

  match '/fb_handler/request_callback/:profile_type' => 'fb_handler#request_callback', :as => 'fb_callback'

  resources :profiles do
    member do
      post 'invite'
    end
  end
  
  scope :controller => :dashboard do
    match "login"
    match "dashboard"
    match "welcome"
    match "contacts"
    match "browse"
    match "inbox"
    match "matchbook"
    match "initialize_profile"
    match "send_invite"
    match "add_catch"
    match "suggest_match"
    match "approve_match"
    match "reject_match"
    match "message"
    match "endorsements"
    match "account"
  end
  
  scope :controller => :conversations do
    match "send_message"
    match "conversation/:id" => :show, :as => "conversation"
  end
  
  resources :connections
  match 'create_match' => 'profiles#create_match'
  
  match "project" => 'static_pages#project'
  match "team" => 'static_pages#team'
  match "login" => 'static_pages#login'
  
  match 'dashboard' => 'yenta_friend#dashboard'
  match 'browse' => 'yenta_friend#browse'
  # match 'connections' => 'yenta_friend#connections'
  match 'chickstud_connections(/:id)' => 'yenta_friend#chickstud_connections', :as => :chickstud_connections
  match 'inbox' => 'yenta_friend#inbox'
  match 'stable' => 'yenta_friend#stable'
  
  
  
  
  root :to => 'dashboard#login'
    
end

app/models/conversation/conversation.rb
class Conversation
  include Mongoid::Document
  include Mongoid::Timestamps
  
  belongs_to :conversable, :polymorphic => true
  has_and_belongs_to_many :inboxes
  has_and_belongs_to_many :participants, :class_name => "Profile"
  embeds_many :messages
  
end

app/models/conversation/inbox.rb
class Inbox
  include Mongoid::Document
  
  belongs_to :profile
  embeds_many :message_references
  
end

app/models/conversation/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps
  
  
  embedded_in :conversation
  belongs_to :profile, :inverse_of => nil
  belongs_to :messageable, :polymorphic => true, :inverse_of => nil
  
  field :from_name
  field :from_icon
  field :body, :default => ""
  
end

app/models/conversation/message_reference.rb
class MessageReference
  include Mongoid::Document
  include Mongoid::Timestamps
  
  belongs_to :conversation, :inverse_of => nil
  belongs_to :profile, :inverse_of => nil
  belongs_to :messageable, :polymorphic => true, :inverse_of => nil
    
  default_scope desc(:created_at)
  
  field :from_name
  field :from_icon
  field :body, :default => ""
  field :content_type, :default => "text"
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def send_message
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.create(params[:message].merge(:profile => current_profile, :from => current_profile.name, :icon_url => current_profile.image_url))
    
    # might as well just send it out over the message channel...
    
    if @message
      # html = render :partial => "posts/#{@post._type.underscore}"
      # Pusher["conversation-#{conversation._id}"].trigger("message", {:html => html})
      # for profile in @conversation.participants do
      #   html = render :partial => "posts/#{@post._type.underscore}"
      #   Pusher["private-#{profile._id}"].trigger('message', {:conversation_id => @conversation._id, :html => html.to_s})
      # end
    end
  end
  def show
    @conversation = Conversation.find(params[:id])
# change this later
		alter = @conversation.participants - current_profile.to_a
		redirect_to profile_path(alter.first)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
- conversation ||= @conversation
%li[conversation]
  = link_to conversation_path(conversation) do
    .row-fluid
      .span10
        %h3= conversation.participants.only(:first_name).collect(&:first_name).join(" + ")
      .span8.well
        - if conversation.messages.any?
          .span1.thumbnail= image_tag conversation.messages.last.icon_url
          %p= conversation.messages.last.body

app/views/conversations/_form.html.haml
= form_for @conversation, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :participant_ids, :class => 'control-label'
    .controls
      = f.text_field :participant_ids, :class => 'text_field'
  .control-group
    = f.label :_id, :class => 'control-label'
    .controls
      = f.text_field :_id, :class => 'text_field'
  .control-group
    = f.label :_type, :class => 'control-label'
    .controls
      = f.text_field :_type, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), conversation_path, :class => 'btn'

app/views/conversations/_history.html.haml
- conversation ||= @conversation
.well
	%section.conversation_history{:id => "conversation_#{conversation._id}_history"}
		/ .page-header
		/ 	%h2
		/ 		Conversation History
				
		%ul.row-fluid.message_wrapper
			- for message in conversation.messages do
				= render :partial => 'conversations/messages/message', :locals => {:message => message}
:javascript
	$(function(){
		alert(pusher);
	})
	

app/views/conversations/_main.html.haml
- conversation ||= @conversation
%section#new_message
	.page-header
		%h1 conversation
	.row-fluid
		= form_for :message, :class => "well form-search", :url => send_message_path, :remote => true do |f|
			= hidden_field_tag :conversation_id, conversation._id
			= f.hidden_field :messageable_type
			= f.hidden_field :messageable_id
			= f.text_field :body, :class => "input-xlarge search-query btn-large" , :placeholder => "Send a message"
			= f.submit "Send", :class =>	"btn btn-large btn-primary"
			- if usertype == "Yentum"	
				= link_to "Send Profile", '#select_catch', "data-toggle" => "modal", :onclick => "$('#select_catch').show.modal();", :class => 'btn btn-large '
= render :partial => 'shared/modal/select_catch'

app/views/conversations/edit.html.haml
- model_class = @conversation.class
%h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/conversations/index.html.haml
- model_class = Conversation.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:participant_ids)
      %th= model_class.human_attribute_name(:_id)
      %th= model_class.human_attribute_name(:_type)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @conversations.each do |conversation|
      %tr
        %td= link_to conversation.id, conversation_path(conversation)
        %td= conversation.participant_ids
        %td= conversation._id
        %td= conversation._type
        %td=l conversation.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_conversation_path(conversation), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), conversation_path(conversation), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_conversation_path, :class => 'btn btn-primary'

app/views/conversations/new.html.haml
- model_class = @conversation.class
%h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/conversations/send_message.js.haml
$('#conversation_#{@conversation._id}_history .message_wrapper').prepend("#{escape_javascript(render :partial => 'conversations/messages/message')}");
$('#message_body').val("");

app/views/conversations/show.html.haml
= content_for :pageheader do
  %h1= @conversation.participants.only(:first_name).collect(&:first_name).join(" + ")
  %p.lead
= content_for :main do
  = render :partial => 'conversations/history', :locals => {:conversation => @conversation}
  = render :partial => 'conversations/main', :locals => {:conversation => @conversation}