config/routes.rb
YentaFriend::Application.routes.draw do
  


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins
  mount RailsAdmin::Engine => '/manage', :as => 'rails_admin'

  get "paypal_express/checkout"
	post "paypal_express/handle_response"
	get "paypal_express/authenticate_redirect"

  match '/fb_handler/request_callback/:profile_type' => 'fb_handler#request_callback', :as => 'fb_callback'

  resources :profiles do
    member do
      post 'invite'
    end
  end
  
  scope :controller => :dashboard do
    match "login"
    match "dashboard"
    match "welcome"
    match "contacts"
    match "browse"
    match "inbox"
    match "matchbook"
    match "initialize_profile"
    match "send_invite"
    match "add_catch"
    match "suggest_match"
    match "approve_match"
    match "reject_match"
    match "message"
    match "endorsements"
    match "account"
  end
  
  scope :controller => :conversations do
    match "send_message"
    match "conversation/:id" => :show, :as => "conversation"
  end
  
  resources :connections
  match 'create_match' => 'profiles#create_match'
  
  match "project" => 'static_pages#project'
  match "team" => 'static_pages#team'
  match "login" => 'static_pages#login'
  
  match 'dashboard' => 'yenta_friend#dashboard'
  match 'browse' => 'yenta_friend#browse'
  # match 'connections' => 'yenta_friend#connections'
  match 'chickstud_connections(/:id)' => 'yenta_friend#chickstud_connections', :as => :chickstud_connections
  match 'inbox' => 'yenta_friend#inbox'
  match 'stable' => 'yenta_friend#stable'
  
  
  
  
  root :to => 'dashboard#login'
    
end

app/views/shared/_chickstud_navigation.html.haml
.navbar.navbar-fixed-top
	.navbar-inner
		.container
			%a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			= link_to "Yenta Friend", root_path, :class => "brand"
			.nav-collapse
				%ul.nav
					%li{}
						= link_to "dashboard", dashboard_path
					- if current_profile.endorsements.any?						
						%li.dropdown{}
							= link_to '#',{ :class => 'dropdown-toggle', 'data-toggle' => 'dropdown'} do
								endorsements 
								%b.caret
							%ul.dropdown-menu
								%li.divider
								- for profile in current_profile.endorsements.collect(&:yentum)
									%li
										= link_to profile_path(profile) do
											= image_tag profile.default_image_url, :size => "25x25"
											= profile.name
					- if current_profile.connections.any?						
						%li.dropdown{}
							= link_to '#',{ :class => 'dropdown-toggle', 'data-toggle' => 'dropdown'} do
								matches
								%b.caret
							%ul.dropdown-menu
								%li.divider
								- for connection in current_profile.connections
									- profile = (connection.partners - current_profile.to_a).first
									%li
										= link_to connection_path(connection) do
											= image_tag profile.default_image_url, :size => "25x25"
											= profile.name
								
					%li{}
						= link_to 'contacts', contacts_path
					/ %li{}
					/	 = link_to 'inbox', inbox_path
					%li
						%a#invite{:href=>"#invite_form", "data-toggle".to_sym => "modal", :onclick => "$('#invite_form').modal()"} Invite
				%ul.nav.pull-right		
					%li.divider-vertical	
					%li.dropdown
						= link_to '#',{ :class => 'dropdown-toggle', 'data-toggle' => 'dropdown'} do
							= image_tag current_user.image_url, :size => "25x25"
							= current_user.first_name + " " + current_user.last_name
							%b.caret
						%ul.dropdown-menu
							= link_to "logout", '#'

app/views/shared/_flash.html.haml
- if error
  .span12.alert.alert-error.well
    %h1 Error
    %hr.soften
    %p= error
- if notice
  .span12.alert.alert-info.well
    %h1 Notice
    %hr.soften
    %p= notice

app/views/shared/_invite_form.html.haml
.modal#invite_form.hide
  = form_for :invite, :url => send_invite_path, :remote => true do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"}x
      %h3 Invite a Friend to Yenta!
    .modal-body
      = f.label :name
      = f.text_field :name
      = f.label :email
      = f.email_field :email
      = f.label :message
      = f.text_field :message
    .modal-footer
      %a.btn.close{"data-dismiss" => "modal"} Cancel
      = f.submit "Send", :class => "btn btn-primary"

app/views/shared/_notice.html.haml
- notice ||= @notice
%li[notice]{:class => "type-#{notice.notice_type}"}
	.row-fluid
		.span2= image_tag notice.icon_url, :size => "50x50", :class => 'thumbnail'
		.span10
			.row-fluid
				.span10{:style=>'margin-top:5px'}
					%p{:style=>'font-size:16px'}= notice.header
					%p{:style=>'color:#999999'}= notice.body
				.span2.pull-right{:style=>'margin-top:5px'}
					- if notice.href
						= link_to notice.href do
							%span.badge.badge-info{:style=>'font-size:12px;padding-top:4px;padding-bottom:4px'}
								%i.icon-chevron-right
%hr.soften

app/views/shared/_yentum_navigation.html.haml
.navbar.navbar-fixed-top
	.navbar-inner
		.container
			%a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
				%span.icon-bar
				%span.icon-bar
				%span.icon-bar
			= link_to root_path, :class => "brand" do
				=image_tag("logo-brand.png")
			.nav-collapse
				%ul.nav
					%li.divider
					%li= link_to "dashboard", dashboard_path
					%li.dropdown{}
						= link_to '#',{ :class => 'dropdown-toggle', 'data-toggle' => 'dropdown'} do
							catches
							%b.caret
						%ul.dropdown-menu
							%li= link_to "matchbook", matchbook_path
							%li.divider
							%li.nav-header catches
							- for profile in current_profile.endorsements.collect(&:chickstud)
								%li
									= link_to profile_path(profile) do
										= image_tag profile.default_image_url, :size => "25x25"
										= profile.name
					%li{}
						= link_to 'contacts', contacts_path
					/ %li{}
					/ 	= link_to 'inbox', inbox_path
					%li
						%a#invite{:href=>"#invite_form", "data-toggle".to_sym => "modal", :onclick => "$('#invite_form').modal()"} Invite
				%ul.nav.pull-right		
					%li.divider-vertical	
					%li.dropdown
						= link_to '#',{ :class => 'dropdown-toggle', 'data-toggle' => 'dropdown'} do
							= image_tag current_user.image_url, :size => "25x25"
							= current_user.first_name + " " + current_user.last_name
							%b.caret
						%ul.dropdown-menu
							= link_to "logout", '#'