config/routes.rb
YentaFriend::Application.routes.draw do
  


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins
  mount RailsAdmin::Engine => '/manage', :as => 'rails_admin'

  get "paypal_express/checkout"
	post "paypal_express/handle_response"
	get "paypal_express/authenticate_redirect"

  match '/fb_handler/request_callback/:profile_type' => 'fb_handler#request_callback', :as => 'fb_callback'

  resources :profiles do
    member do
      post 'invite'
    end
  end
  
  scope :controller => :dashboard do
    match "login"
    match "dashboard"
    match "welcome"
    match "contacts"
    match "browse"
    match "inbox"
    match "matchbook"
    match "initialize_profile"
    match "send_invite"
    match "add_catch"
    match "suggest_match"
    match "approve_match"
    match "reject_match"
    match "message"
    match "endorsements"
    match "account"
  end
  
  scope :controller => :conversations do
    match "send_message"
    match "conversation/:id" => :show, :as => "conversation"
  end
  
  resources :connections
  match 'create_match' => 'profiles#create_match'
  
  match "project" => 'static_pages#project'
  match "team" => 'static_pages#team'
  match "login" => 'static_pages#login'
  
  match 'dashboard' => 'yenta_friend#dashboard'
  match 'browse' => 'yenta_friend#browse'
  # match 'connections' => 'yenta_friend#connections'
  match 'chickstud_connections(/:id)' => 'yenta_friend#chickstud_connections', :as => :chickstud_connections
  match 'inbox' => 'yenta_friend#inbox'
  match 'stable' => 'yenta_friend#stable'
  
  
  
  
  root :to => 'dashboard#login'
    
end

app/models/profile/chickstud.rb
class Chickstud < Profile
  
  belongs_to :yentum
  has_and_belongs_to_many :matches
  has_many :endorsements, :dependent => "destroy"
  
  field :interested_in
  field :about
  field :invited, :default => false
  
  after_create :set_defaults
  before_save :set_name
  
  def connections
    partner_connections
  end

  def set_name
    self.name = first_name + " " + last_name
  end
  
  def format_fields

  end
  
  def set_defaults
    update_attribute(:interested_in, (interested_in.nil? ? (gender == "male" ? "women" : "men") : interested_in.gsub(" ", "_").underscore))
  end
  
end

app/helpers/chickstuds_helper.rb
module ChickstudsHelper
end

app/views/profiles_old/chickstuds/_form.html.haml
- profile ||= @profile
.page-header 
  %h1
    Edit Information
    %small
      = link_to_function "Cancel", '$("#information").html("#{escape_javascript(render :partial => "profiles/chickstuds/information", :locals => {:profile => profile})}");'
.row
  = form_for profile, :url => profile_path, :class => "well form", :remote => true do |f|
    = f.label :first_name
    = f.text_field :first_name, :class => "span3"
    = f.label :last_name
    = f.text_field :last_name, :class => "span3"
    = f.label :gender
    = f.select :gender, options_for_select(%w{male female}.map{|gender| [gender.humanize, gender]}, profile.gender), :class => "span3"
    = f.label :interested_in
    = f.select :interested_in, options_for_select(%w{men women men_and_women}.map{|interested_in| [interested_in.humanize, interested_in]}, profile.interested_in), :class => "span3"
    = f.label :endorsement
    = f.text_field :endorsement, :class => "span3"
    = f.submit "Update Information", :class => "btn btn-primary span3"

app/views/profiles_old/chickstuds/_information.html.haml
.page-header 
  %h1
    Information
    %small
      - if chickstud_belongs_to_yentum?(profile)
        = link_to_function "Edit", '$("#information").html("#{escape_javascript(render :partial => "profiles/chickstuds/form", :locals => {:profile => profile})}");'
  %hr.soften
  %table.table.table-striped
    %tbody
      %tr
        %td
          %b Name
        %td= profile.name
      %tr
        %td
          %b Picture
        %td= image_tag profile.fb_image_url("normal")
      %tr
        %td
          %b Gender
        %td= profile.gender.capitalize
      %tr
        %td
          %b Interested In
        %td= profile.interested_in.humanize
      %tr{:colspan => 2}
        %td= link_to "View more information", "http://facebook.com/#{profile.fb_uid}", :target => "_blank"

app/views/profiles_old/chickstuds/_profile.html.haml
.portthumb.span3[profile]{:class => "gender-#{profile.gender} privacy-#{profile.privacy}"}
  = link_to profile_path(profile), :rel => "tooltip", :title => profile.endorsement, :class => "thumbnail" do
    = image_tag( profile.fb_image_url("large"), :height => "160")
    %h2= profile.first_name

app/views/profiles_old/chickstuds/show.html.haml
- yentum ||= profile.yentum
= content_for :subnav do
  %ul.nav.nav-pills
    %li= link_to "about", '#about', :class => 'anchorLink'
    %li= link_to "connections", '#connections', :class => 'anchorLink'
= content_for :pageheader do
  .row
    .span12
      .row
        .span7
          %h1
            = profile.name
        .span5
          %h2
            %blockquote
              - if chickstud_belongs_to_yentum?(profile)
                = form_for profile, :url => profile_path, :remote => true do |f|
                  = f.text_field :endorsement, :placeholder => "endorsement", :type => 'input-search'
                  = f.submit "Save"
              - else
                %em= "\"#{profile.endorsement}\"" unless profile.endorsement.blank?
                %small
                  = link_to "#{yentum.name}", profile_path(yentum)
                  \, Yenta      
  %p.lead
      
= content_for :main do
  .container
    %section#about
      .page-header
        %h1
          = "About #{profile.first_name}"
          %small= "Find out more about #{profile.pronoun_obj}!"
      .page-body
        .row
          .span3
            = image_tag profile.fb_image_url("large")
          .span9
            %table.span9.table-striped
              %tbody
                %tr
                  %th Name
                  %td= profile.name
                %tr
                  %th Yenta
                  %td= link_to yentum.name, profile_path(yentum)
                %tr
                  %th Member Since
                  %td= profile.member_since
                %tr
                  %th Gender
                  %td= profile.gender.humanize
                %tr
                  %th Interested In
                  %td= profile.interested_in.humanize            
                %tr
                  %th Connections
                  %td= link_to "#{profile.connections.count} connections", '#connections', :class => 'badge anchorLink'

                %tr
                  %td.pull-right{:colspan => 2}
                    = link_to 'Learn more', "http://facebook.com/#{profile.fb_uid}", :target => "_blank"
                    %span.muted (external link)
    %section#connections
      .page-header
        %h1 
          Connections
          %small
            = "See the people that #{profile.first_name} has been connecting with."
            .pull-right
              %span.badge= profile.connections.count
              Connections
        - if profile.private? && chickstud_belongs_to_yentum?(profile)
          .well.alert-info
            %h4 This profile has not been made public.
            %p= "Until you make this profile public no one else can recommend matches for #{profile.first_name}."
            %hr.soften
            = link_to "Make Profile Public", "#make_public", "data-toggle".to_sym => "modal", :class => 'btn btn-primary'
        - else
          = link_to "Suggest Connection", '#new_connection', 'data-toggle'=> 'modal', :class => 'btn btn-primary modal-link'      
      .page-body  

        .row
          - for connection in profile.connections do
            = render :partial => 'connections/connection', :locals => {:connection => connection}
  .modal#new_connection.fade
    = form_for :connection, :url => connections_path, :remote => true do |f|
      = fields_for :profiles do |profile_fields|
        %span.current-profile= profile_fields.text_field :profile1, :value => profile._id
        %span.connect-profile= profile_fields.text_field :profile2
    .modal-header
      %a.close{"data-dismiss".to_sym => "modal"} x    
      %h2= "Suggest a Connection for #{profile.first_name}"
    .modal-body
      %table.table.table-striped
        %tbody#stable 
          - for _profile in (current_stable - [profile]) do
            %tr[_profile]{:class => "gender-#{_profile.gender} privacy-#{_profile.privacy}"}
              %td= image_tag _profile.fb_image_url, :size => "40x40"
              %td{:colspan => 2}
                %h4= _profile.name
              %td
                = link_to 'Select', '#', :onclick => "$('#new_connection input[name=\"profiles[profile2]\"]').val('#{_profile._id}');$('#new_connection form').submit();", :class => 'btn btn-primary'
  .modal#make_public.fade
    .modal-header
      %a.close{"data-dismiss".to_sym => "modal"} x    
      %h3= "Make #{profile.first_name}'s profile public."
      %p= "Send an invite to #{profile.first_name}.  Once #{profile.pronoun_subj} accepts other yentas will be able to view #{profile.pronoun_obj} profile and suggest matches."
    .modal-body
      %p= "How would you prefer to invite #{profile.pronoun_obj}?"
      .row
        .span6.well
          %h3 Email Invite
          = form_for :invite, :url => invite_profile_path(profile._id), :remote => true do |f|
            = f.label :email
            = f.email_field :email, :placeholder => "#{profile.first_name}'s Email Address", :class => 'input-xlarge span5'
            = f.label :message
            = f.text_field :message, :placeholder => "Come checkout YentaFriend and get connected!", :class => 'input-xlarge span5'
            %br
            = f.submit "Invite", :class => 'btn btn-primary'
        %hr.soften    
        .span6.well
          %h3 Facebook Invite
          = link_to "Invite on Facebook", '#', :id => 'app_invite'
  / .modal#update_profile.fade
  /   .modal-header
  /     %h2= "Update #{profile.first_name}'s Information"
  /     %a.close{"data-dismiss".to_sym => "modal"} x
  /   .modal-body
  /     = render :partial => 'profiles/chickstuds/form', :locals => {:profile => profile}
  / 